CREATE TABLE public.restaurant (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	registerNumber varchar(255) NULL,
	updatedDate timestamp NULL,
	createdDate timestamp NULL,
	name varchar(255) NULL,
	owner varchar(255) NULL,
	mapPosition_id int8 NULL,
	CONSTRAINT restaurant_pkey PRIMARY KEY (id)
);


-- public.Restaurant foreign keys

ALTER TABLE public.restaurant ADD CONSTRAINT fkdfbggt9ievc4ev74wl3tdnscl FOREIGN KEY (mapposition_id) REFERENCES mapposition(id);

-- public.prato definition

-- Drop table

-- DROP TABLE public.prato;

CREATE TABLE public.dish (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	description varchar(255) NULL,
	name varchar(255) NULL,
	price numeric(19,2) NULL,
	restaurant_id int8 NULL,
	CONSTRAINT dish_pkey PRIMARY KEY (id)
);


-- public.prato foreign keys

ALTER TABLE public.dish ADD CONSTRAINT fk43yo4ddilkvn6ebgfcx2vnqs7 FOREIGN KEY (restaurant_id) REFERENCES restaurant(id);
